- .flake8
- .github/workflows/codeql-analysis.yml
- .yamllint
- taskcluster/ci/tests/kind.yml
I added this workflow via the Github UI, but apparently it doesn't mesh with our yamllint setup.
> ci: fix yamllint errors in new Github codeql workflow

- taskcluster/docker/index-task/Dockerfile
- taskcluster/docker/index-task/package.json
- taskcluster/docker/index-task/yarn.lock
This upgrades the index-task image:
node: 10 -> 16
taskcluster-client 12 -> 44
> chore(deps): upgrade index-task image

- src/taskgraph/util/schema.py
- test/test_util_schema.py
This is a pre-requisite to merging `transforms/base.py` between the taskgraphs.
> Sync various changes from gecko_taskgraph that are reachable from `transforms.base`

- src/taskgraph/actions/registry.py
- src/taskgraph/transforms/job/__init__.py
- src/taskgraph/util/python_path.py
This syncs a change from `gecko_taskgraph`.
> refactor: factor code for importing sibling modules into a utility file

- docs/howto/docker.rst
- docs/howto/index.rst
> docs: add howto page for using docker images

- docs/howto/create-actions.rst
- docs/howto/index.rst
> docs: add howto page for creating actions

- docs/glossary.rst
- docs/howto/create-actions.rst
While refactoring the firefox-source-docs, I came across a few things that were missed here. This PR adds them.
> Miscellaneous doc improvements

- src/taskgraph/util/schema.py
In Gecko there's a lint check to prevent the use of
'whitelist/blacklist', and there's an exception for this case.
Since we're gearing up to release Taskgraph 2.0 anyway, might as well
make the switch.
> refactor!: rename taskgraph.util.WHITELISTED_SCHEMA_IDENTIFIERS

- src/taskgraph/util/verify.py
- test/conftest.py
- test/test_optimize.py
- test/test_util_verify.py
This syncs a change from Gecko.
Jira: RELENG-852
> fix: improve error handling in `verify_task_graph_symbol` verification

- src/taskgraph/actions/util.py
Update another optimize_task_graph caller for the new function signature.
Fixes #99
> actions: fix create_tasks after #82

- src/taskgraph/transforms/task.py
This was added in https://github.com/taskcluster/taskcluster/pull/5695.
CC @jschwartzentruber @matt-boris @lotas
> Support docker-worker capability disableSeccomp

- docs/concepts/task-graphs.rst
After needing to explain how to write a dependency, I realized the docs on this topic were sorely lacking.
> docs: add better documentation on dependencies

- src/taskgraph/transforms/docker_image.py
> chore: update 'image_builder' image to 5.0.0

- src/taskgraph/run-task/run-task
- taskcluster/docker/python/Dockerfile
- test/test_scripts_run_task.py
> fix: run-task git checkout for non-default branch

- src/taskgraph/decision.py
- test/test_decision.py
> fix: `DONTBUILD` on `github-push`.

- src/taskgraph/run-task/run-task
https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
> run-task: update github SSH host key

- src/taskgraph/run-task/fetch-content
- src/taskgraph/run-task/robustcheckout.py
- test/test_scripts_fetch_content.py
This imports changes already made in mozilla-central.
Helps mitigate https://bugzilla.mozilla.org/show_bug.cgi?id=1821513
> Add timeouts for http connections in robustcheckout and fetch-content (bug 1821513)

- .gitignore
- src/taskgraph/generator.py
- taskcluster/ci/doc/kind.yml
fix: Added exception message for invalid depenedency of a task #230
> fix: Added exception message for invalid dependency of a task

- .gitignore
.DS_STORE is now ignored by git
> .DS_STORE added to .gitignore

- .gitignore
a simple fix to add the python virtual environement to the .gitignore
@JohanLorenzo can you review it? :)
> fix: add the python virtual environment to .gitignore

- CHANGELOG.md
- src/taskgraph/run-task/run-task
Added the call to `print_line` for logging the command used to inoke the run-task script. Used `sys.argv` to capture the command invoking `run task`
> Logging the command used to invoke run-task

- src/taskgraph/transforms/from_deps.py
> from_deps: use validate_schema to avoid breaking --fast

- src/taskgraph/transforms/job/__init__.py
I was trying to use this in the task transforms and ran into a schema error.
> Add deadline-after to job_description_schema

- docs/tutorials/connecting-taskcluster.rst
- docs/tutorials/getting-started.rst
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1857024.
> chore: update community-tc-config links [skip ci]

- src/taskgraph/util/taskcluster.py
Refs: 4f364e66823cd4627175f3767c4d00b17b26fd11
Issue: #400
> revert: "Log the body of taskcluster errors"

- src/taskgraph/optimize/base.py
Very minor things that were useful when I was doing some debugging earlier.
> feat: improve logging in some optimization code

- template/{{cookiecutter.project_name}}/taskcluster.github.yml
I didn't want to enable tasks on release by default, but let's at least set all the variables properly so enabling github-release tasks becomes easier.
> fix(init): properly support github-release variables in .tc.yml template

- src/taskgraph/util/taskcluster.py
- test/test_util_taskcluster.py
This greatly improves performance of get_ancestors for certain inputs.
> feat: memoize get_task_definition and _get_deps

- src/taskgraph/util/parameterization.py
- src/taskgraph/util/taskcluster.py
- test/test_util_parameterization.py
- test/test_util_taskcluster.py
> fix: support 'artifact-reference' with private artifacts

- src/taskgraph/util/cached_tasks.py
- test/test_util_cached_tasks.py
BREAKING CHANGE: changed cached_task pull request index route format
> refactor!: remove 'head_ref' from cached_task PR route

- pyproject.toml
Following the advice of nedbat:
https://nedbatchelder.com/blog/202008/you_should_include_your_tests_in_coverage.html
> ci: add test directory to coverage results

- src/taskgraph/run-task/fetch-content
- test/test_scripts_fetch_content.py
> Bug 1796139 - Pull in fetch-content changes from mozilla-central

- taskcluster/docker/python/Dockerfile
To adhere to https://github.com/taskcluster/taskgraph/blob/f20ebf1921e2feed7682b074f91fc96609d5319b/src/taskgraph/util/docker.py#L103-L106
> Update Dockerfile special `ARG` syntax

- src/taskgraph/run-task/run-task
- src/taskgraph/transforms/run/__init__.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1906899
> Remove unused resource-monitor code
