taskcluster/taskgraph

.taskcluster.yml

Now that we don't need to trigger builds via the rtd webhook, Taskgraph
tasks aren't depending on any secrets and there's no reason to have the
pullRequest policy set to collaborators.

ci: change pullRequest policy to public

---

CODE_OF_CONDUCT.md
CONTRIBUTING.rst
README.rst
docs/contributing.rst

A README should primarily be about telling readers what the repo is about, as well as provide some links to additional docs / context. Information about how to contribute doesn't need to be front and centre and instead should be in a dedicated CONTRIBUTING file.
This also adds a 'How It Works' section to the README and the
CODE_OF_CONDUCT file.

docs: refactor contributing docs out of README

---

.taskcluster.yml

We're going to be adding a codecov token as a secret, so setting the PR
policy back to collaborators to avoid leaking it.

ci: set PR policy back to 'collaborators'

---

src/taskgraph/transforms/task.py

The `hashlib.sha256` function requires bytes, so this has been broken since
we switched to Python 3.

fix: encoding error when using out of tree images

---

tox.ini

The 'run-task' scripts weren't previously being picked up by the
coverage report as it isn't a proper Python module. But passing in the
path to this directory explicitly to 'pytest-cov' seems to do the trick.

ci: ensure 'run-task' scripts are included in coverage report

---

src/taskgraph/run-task/run-task
src/taskgraph/test/test_scripts_run_task.py

When we run VPN tasks on [win2012 workers](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/taskcluster/ci/config.yml#L40) they run successfully but they fail to clean up fetched content.
Here's one of these [tasks](https://firefox-ci-tc.services.mozilla.com/tasks/KcekQk81SPuSzG9obKpkMw/runs/0/logs/public/logs/live.log).
Here's the error:
```
Traceback (most recent call last):
File "run-task", line 1118, in <module>
sys.exit(main(sys.argv[1:]))
File "run-task", line 1113, in main
shutil.rmtree(fetches_dir)
File "C:\mozilla-build\python3\lib\shutil.py", line 494, in rmtree
return _rmtree_unsafe(path, onerror)
File "C:\mozilla-build\python3\lib\shutil.py", line 384, in _rmtree_unsafe
_rmtree_unsafe(fullname, onerror)
File "C:\mozilla-build\python3\lib\shutil.py", line 384, in …
```

fix: permission error when cleaning up fetches directory in run-task

---

CHANGELOG.md
setup.py

Version bumping to pick up Gabriel's Windows cleanup fixes so we can try them out in `mozilla-vpn-client`.

chore: version bump to 1.5.0

---

src/taskgraph/test/conftest.py
src/taskgraph/test/data/taskcluster/scripts/toolchain/run.sh
src/taskgraph/test/test_transforms_job.py
src/taskgraph/test/test_transforms_job_toolchain.py

This is in preparation for supporting `generic-worker` in toolchains.

test: add a test for job/toolchain.py

---

docs/howto/bootstrap-taskgraph.rst
src/taskgraph/run-task/run-task

Currently when installing pip dependencies via the
`<REPO>_PIP_REQUIREMENTS` environment variable, `run-task` explicitly
passes in the `--require-hashes` option. This makes it difficult to test
against pre-release versions of Taskgraph since VCS urls do not support
hashes (https://github.com/pypa/pip/issues/6469).
Luckily when `pip` encounters a requirements with `--hash`, the
`--require-hashes` flag is implied. This means that if `run-task`
doesn't explicitly pass it in, we'll be able to test against pre-release
versions of taskgraph by adding the git URL and then simply *not* using
the `--generate-hashes` flag in `pip-compile`. But in production we'd
still get hash verification.
This does loosen restrictions a bit, since previously a repo would have
no choice other than to use hashes. …

fix(run-task): don't explicitly pass '--require-hashes'

---

src/taskgraph/run-task/run-task
src/taskgraph/test/test_scripts_run_task.py

This patch fixes the git clean checkout regression introduced in #22
I updated the unit test to account for this case, and I added a log warning where the remove function was failing silently.

Fix the git clean checkout regression

---

CHANGELOG.md
setup.py

Patch version to fix Github clean up regression.
See #22 and #44

chore: version bump to 1.5.1

---

src/taskgraph/test/conftest.py
src/taskgraph/test/test_transforms_job.py
src/taskgraph/transforms/job/__init__.py

The previous pull request purported to add the 'toolchain-env' feature,
however I neglected to add the bits to the `use_fetches` transform that
actually makes use of it.
This adds the missing glue along with a test to make sure it's working.

fix: hook up `toolchain-env` attribute to `use_fetches` transform

---

src/taskgraph/transforms/job/__init__.py

This key should have been forwarded from the task_description_schema,
but was accidentally ommitted.

fix: add 'if-dependencies' key to job_description_schema

---

src/taskgraph/util/schema.py

This syncs a change from `gecko_taskgraph`.
Jira: RELENG-888

fix: allow json-e keys in schema identifiers

---

docs/concepts/optimization.rst
docs/reference/index.rst
docs/reference/optimization-strategies.rst
docs/reference/source/taskgraph.actions.rst
docs/reference/source/taskgraph.loader.rst
docs/reference/source/taskgraph.optimize.rst
docs/reference/source/taskgraph.rst
docs/reference/source/taskgraph.transforms.job.rst
docs/reference/source/taskgraph.transforms.rst
docs/reference/source/taskgraph.util.rst
src/taskgraph/actions/retrigger.py
src/taskgraph/actions/util.py
src/taskgraph/generator.py
src/taskgraph/optimize/__init__.py
src/taskgraph/optimize/base.py
src/taskgraph/optimize/strategies.py
src/taskgraph/util/taskcluster.py
test/conftest.py
test/test_optimize.py
test/test_optimize_strategies.py
test/test_util_taskcluster.py

The optimization logic between Gecko and standalone is nearly the same, but Gecko has a few extra features that would be nice to incorporate into Taskgraph. This PR will make the logic identical such that Gecko can remove its copy.
This contains several backwards incompatible changes, as such I'll be doing a major version bump after this lands.
I recommend reviewing this commit by commit.

Sync remaining optimization features from Gecko

---

docs/concepts/kind.rst
docs/howto/docker.rst
docs/tutorials/creating-a-task-graph.rst
src/taskgraph/loader/transform.py
src/taskgraph/transforms/docker_image.py
src/taskgraph/transforms/fetch.py
src/taskgraph/transforms/job/__init__.py
src/taskgraph/transforms/task.py
src/taskgraph/util/docker.py
taskcluster/ci/codecov/kind.yml
taskcluster/ci/doc/kind.yml
taskcluster/ci/docker-image/kind.yml
taskcluster/ci/fetch/kind.yml
taskcluster/ci/tests/kind.yml
test/conftest.py
test/test_generator.py

This is a straight rename from job -> task in keys in the kind.yml
files.
Issue: #25

refactor!: rename 'job*' keys in transform loader to 'task*'

---

src/taskgraph/morph.py
test/test_morph.py

This will allow Gecko to use `taskgraph.morph.morph` while still registering its own custom morphs.

feat(morph): ability for consumers to register custom morphs

---

src/taskgraph/generator.py
src/taskgraph/transforms/base.py
src/taskgraph/transforms/cached_tasks.py
src/taskgraph/transforms/code_review.py
src/taskgraph/transforms/docker_image.py
src/taskgraph/transforms/job/__init__.py
test/test_transforms_job.py

BREAKING CHANGE: TransformConfig.kind_dependencies_tasks has changed
from a list to a dict.
This change syncs functionality with gecko_taskgraph. I think it's
better to go this way (rather than changing gecko_taskgraph to a list),
as a dict makes containment operations much simpler when comparing
labels. E.g:
https://searchfox.org/mozilla-central/rev/6ec440e105c2b75d5cae9d34f957a2f85a106d54/taskcluster/gecko_taskgraph/transforms/partner_attribution.py#63
Jira: RELENG-852
Issue: #28

refactor!: make TransformConfig.kind_dependencies_tasks a dict

---

docs/tutorials/example-taskcluster.yml

Fixes #97.
Following the docker-worker payload [here](https://docs.taskcluster.net/docs/reference/workers/docker-worker/payload).

fix(docs): fix `.taskcluster.yml` payload schema

---

src/taskgraph/transforms/task.py
test/conftest.py
test/test_transforms_task.py

firefox-android is a private github repo accessed via ssh, so the base repository looks like "git@github.com:mozilla-mobile/firefox-android.git". Existing code for constructing the tc-treeherder route's base_project on pull request extracts "firefox-android.git" from the base repo, resulting in a route like "queue:route:tc-treeherder.v2.firefox-android.git-pr..." instead of the desired "queue:route:tc-treeherder.v2.firefox-android-pr..."

Bug 1786535 - Trim ".git" from tc-treeherder route's project

---

requirements/base.txt
src/taskgraph/parameters.py

The untrimmed project name from this function is breaking `taskgraph test-action-callback`

Trim .git from project in taskgraph.parameters._get_defaults

---

src/taskgraph/parameters.py
test/test_parameters.py

This fixes `mach bootstrap`'s InvalidRepoUrlError issues with a remote like "git@example.com:gecko".
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1791852

Catch InvalidRepoUrlError and fail gracefully.

---

src/taskgraph/generator.py

This ensures projects that extend Taskgraph have an opportunity to set things up before we start running verifications (which often cause many modules to be imported.
This syncs a change with Gecko taskgraph.

fix: run initial verifications after 'taskgraph.register'

---

src/taskgraph/generator.py

This ensures that a project's custom parameters are registered when using this function.
Syncs a change from gecko_taskgraph.

fix: use 'parameters_loader' in generator.load_tasks_for_kind

---

.taskcluster.yml
taskcluster/ci/codecov/kind.yml
taskcluster/test/params/main-repo-pull-request-untrusted.yml

This means pull requests opened by non-collaborators will assume a different role and have a different set of scopes associated to them.
For taskgraph, the only task we'd want to limit is the `codecov-upload` one to avoid leaking the codecov API token. So we add a `run-on-tasks-for` key here which will filter out tasks_for == "github-pull-request-untrusted".

ci: switch to the 'public_restricted' pull request policy

---

src/taskgraph/transforms/task.py

This fixes a scope error for untrusted PRs

fix: ensure 'github-pull-request-untrusted' uses proper treeherder route

---

src/taskgraph/run-task/run-task
src/taskgraph/transforms/job/common.py
src/taskgraph/transforms/job/run_task.py
test/test_transforms_job_run_task.py

Gecko is dropping this in
https://bugzilla.mozilla.org/show_bug.cgi?id=1793923, and other taskgraph users shouldn't need it either.

Drop support for pinning hg.mozilla.org TLS certificate fingerprint

---

.taskcluster.yml

Previously we were treating all non-main branches as level 3, which means anyone could run level 3 tasks (luckily Taskgraph doesn't really have any sensitive ones anyway).
By simply not running the tasks on non-main branch we also prevent duplicate tasks on PRs opened within the canonical repository (as opposed to a fork).

ci: only run `github-push` tasks on main

---

pyproject.toml
src/taskgraph/run-task/fetch-content
src/taskgraph/run-task/robustcheckout.py
src/taskgraph/run-task/run-task
src/taskgraph/transforms/fetch.py
src/taskgraph/transforms/job/__init__.py
test/test_scripts_fetch_content.py

This brings all changes to gecko's version of fetch-content from the last couple of years to upstream taskgraph.
In addition this updates the robustcheckout hg extension to the latest version, and reformats the scripts in the `run-task` directory with black.
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1796139

Bug 1796139 - deduplicate fetch-content with gecko

---

src/taskgraph/main.py

When using the formatter that just outputs the labels, tasks will appear all out of order due to how dependencies are added. When the graph is large, it's very difficult to find the task you're looking for. Sorting the output makes this much better.

fix: sort taskgraph label output

---

src/taskgraph/parameters.py

When the remote URL is rejected as unsupported, it's helpful to print a list of the platforms that are supported and explain that the default remote should be changed to point to a repository on one of these platforms.
**Note:** this patch depends on https://github.com/mozilla-releng/mozilla-repo-urls/pull/6 and shouldn't be merged until that patch is merged.

fix: Catch `UnsupportedPlatformError` in order not to bust mach commands (bug 1793219)

---

src/taskgraph/actions/rebuild_cached_tasks.py
test/data/taskcluster/ci/config.yml
test/test_actions_rebuild_cached_tasks.py

This copies the existing action in Gecko to standalone Taskgraph + adds a test.

feat: add an action to rebuild cached tasks

---

src/taskgraph/transforms/task.py

This reverts PR #140, since it is no longer needed. The underlying docker-worker feature was removed in taskcluster/taskcluster#5800 when it was [discovered to be superfluous](https://github.com/taskcluster/taskcluster/pull/5800#issuecomment-1330766821).

Revert "Support docker-worker capability disableSeccomp"

---

taskcluster/docker/decision-mobile/Dockerfile

Reverts taskcluster/taskgraph#160
See https://github.com/mozilla-mobile/firefox-android/pull/340. This approach didn't pay off after all.

Revert "Bug 1788606 - mobile: add gradle cache as a mounted volume"

---

src/taskgraph/run-task/fetch-content

Many projects use .tgz as a shortcut to .tar.gz. Support that pattern.

Bug 1798930 - Support .tgz extension in fetch-content

---

src/taskgraph/transforms/job/toolchain.py
test/test_transforms_job_toolchain.py

This ensures we forward unrecognized schema arguments to the `run_task.py` transforms. Validation of these arguments will then happen over there.

feat: support extra 'run-task' features in toolchains

---

test/test_decision.py

We already mock out decision._determine_more_accurate_base_rev, so I'm guessing we want to do this as well. Without it, these tests end up running some `util/vcs.py` code against your local taskgraph repo. In my case, this [fails to guess the default branch](https://github.com/taskcluster/taskgraph/blob/936142a8c73510d0a0b530ac4a9a16d54cced6c9/src/taskgraph/util/vcs.py#L399-L412) because I have multiple remotes configured.

Mock out decision._determine_more_accurate_base_ref in decision tasks

---

src/taskgraph/decision.py
test/test_decision.py

Reverts taskcluster/taskgraph#191 for breaking unit tests[1]: 
```
[task 2023-02-24T13:41:13.181Z] =================================== FAILURES ===================================
[task 2023-02-24T13:41:13.181Z] ___________________ TestGetDecisionParameters.test_dontbuild ___________________
[task 2023-02-24T13:41:13.181Z] 
[task 2023-02-24T13:41:13.181Z] self = <test.test_decision.TestGetDecisionParameters testMethod=test_dontbuild>
[task 2023-02-24T13:41:13.181Z] 
[task 2023-02-24T13:41:13.181Z]     def test_dontbuild(self):
[task 2023-02-24T13:41:13.181Z]         repo_mock = unittest.mock.MagicMock()
[task 2023-02-24T13:41:13.181Z]         repo_mock.commit_message = "Add FOO DONTBUILD"
[task 2023-02-24T13:41:13.181Z]     
[task 2023-02-24T13:41:13.181Z] …
```

Revert "fix: `DONTBUILD` on `github-push`."

---

docs/howto/bootstrap-taskgraph.rst

Since commit 58ab2b74e436aab766b8f1ae3c2c346a888ef30c "decision: update docker image to Ubuntu 20.04 and Mercurial 5.3.1", the decision and decision-mobile images use python 3.8.

docs: update python version for the decision image

---

src/taskgraph/transforms/job/run_task.py
test/data/command_context.yaml
test/test_transforms_job_run_task.py

This can be useful in cases where context is shared across many tasks and/or kinds, so it can be centralized elsewhere.
This is largely same as the Gecko specific version I wrote in https://phabricator.services.mozilla.com/D170242, with the exception that there's no root or base directory assumed -- the file path will be treated as is (whether it's absolute or remote).

Add support for command-context.from-file in run-task

---

src/taskgraph/actions/registry.py
src/taskgraph/util/docker.py
src/taskgraph/util/yaml.py
test/test_util_yaml.py

It _feels_ like this ought to be safe to do everywhere, but it's difficult to shake the feeling that there may be some edge cases lurking out there where a file would _want_ to be reloaded. The only plausible way this seems like it _should_ happen is in a scenario where a yaml file is being written and loaded during taskgraph generation...which is pretty far fetched, and possibly even something we would explicitly not support. Any such scenario would reduce the determinism of taskgraph, which seems like something that should be avoided.
I did test in Gecko with a number of different parameter sets, and the taskgraphs came out identical with and without this memoized - so that's _some_ level of assurance that this is not totally out there.

Memoize taskgraph.util.load_yaml 

---

src/taskgraph/run-task/fetch-content

We already unzip tar files quietly, we probably ought to do the same for zips. It's been noted that this is very spammy in logs.

unzip files in `fetch-content` quietly

---

src/taskgraph/decision.py
test/test_decision.py

If the commit message of a `github-push` or `hg-push` contains `dontbuild` (all caps), the build should be skipped. Previously, this was supported for only `hg-push`. This commit adds support for `github-push` and provides tests to make sure the behavior is as expected.
fixes: #189 #191

fix: `dontbuild` on `github-push`.

---

setup.py
src/taskgraph/main.py
src/taskgraph/util/path.py

BREAKING CHANGE: Python 3.6 is no longer supported.

refactor!: drop support for Python 3.6

---

docs/concepts/kind.rst
docs/concepts/loading.rst
docs/tutorials/creating-a-task-graph.rst
src/taskgraph/generator.py
src/taskgraph/loader/default.py
src/taskgraph/transforms/task.py
src/taskgraph/util/treeherder.py
template/{{cookiecutter.project_name}}/taskcluster/ci/hello/kind.yml
test/fixtures/gen.py
test/test_generator.py
test/test_transforms_task.py

This is a partial fix #184, dealing with the idea of a default loader, transforms, and autogenerated treeherder symbols. The individual commits have commentary on each of these - but it's largely in line with what's described in the issue.

Add smarter defaults for loaders, transforms, and treeherders

---

src/taskgraph/generator.py
src/taskgraph/transforms/docker_image.py
test/test_transform_docker_image.py

This PR addresses issue #190. Currently, when the `dontbuild` keyword is provided, no tasks are scheduled, but the build-docker tasks are still silently injected in between the target and optimized phases. This behavior is inconsistent with the intended use of the `dontbuild` keyword and can cause confusion.
This PR modifies the taskgraph to remove the silent injection of build-docker tasks by enabling `always-target` for them to explicitly state their generation.

fix: build-docker silent injection with `dontbuild` bug.

---

docs/concepts/transforms.rst
src/taskgraph/generator.py
test/data/taskcluster/test_taskgraph/transforms/foo.py
test/test_generator.py

This is a minor quality of life improvement to simplify kind.yml files a small amount.

feat: use 'transforms' as object by default when resolving references

---

src/taskgraph/transforms/job/run_task.py
test/test_transforms_job_run_task.py

The current Python path to Mac hardcodes Python 3.6 into the name, and on Windows it assumes `mozilla-build` is being used!
While we can (and should) update this to a better location (I see Gecko moved to `/usr/local/bin/python3`), forcing hardcoded Python path at all is somewhat problematic as it makes assumptions about the workers that are not necessarily going to be valid.
I think ideally we would just run `./run-task` all the time and it should just work, maybe the shebang could be changed to `/usr/bin/env python3`? However I'm a bit afraid that doing this is going to break certain workers.
So this implements a method to override the command used to invoke `run-task` from a task definition. This way if we break things, there will be a viable workaround ready to go.
I'm not super happy …

feat: implement a 'run-task-command' key in run_task.py transforms

---

src/taskgraph/run-task/run-task

https://bugzilla.mozilla.org/show_bug.cgi?id=1829604

run-task: abort git clone/fetch if http transfer is too slow

---

src/taskgraph/transforms/task.py
test/fixtures/gen.py
test/test_transforms_task.py

It turns out that `build_task` needs to run after `add_index_routes` (big whoops on my part...).
Fixing this means extracting all the treeherder goop from `build_task` so we can run it before `add_index_routes`. In the process I noticed that my original patch ended up adding unnecessary `kind` and `platform` keys to the `extra.treeherder` object, which I'm also correcting here. (This was due to using the `treeherder` object as both an intermediary object to merge the defaults and task provided treeherder information and the final thing we set on the task - something we weren't doing before.)

Rework treeherder defaults to fix indexes that get dropped sometimes.

---

src/taskgraph/main.py

Without this if a base or head branch name contains a `/` character we'll try to write a temporary file to a nonexistent directory and die.

cli: deal with branch names with `/` in them

---

.taskcluster.yml

This seems to be something that Taskcluster started to complain about since the latest deploy.

ci: fix multiple truthy conditions in base_ref $switch

---

docs/reference/index.rst
docs/reference/source/taskgraph.transforms.rst
docs/reference/transforms/from_deps.rst
docs/reference/transforms/index.rst
src/taskgraph/transforms/from_deps.py
src/taskgraph/util/attributes.py
test/fixtures/gen.py
test/test_optimize.py
test/test_transforms_from_deps.py

These transforms will implement part of the work that the multi_dep loader is doing in other projects.
Issue: #227

feat: create transforms for adding dependencies

---

src/taskgraph/transforms/from_deps.py
src/taskgraph/util/dependencies.py

This fixes a bug that results in a schema validation error anytime a custom group-by function is used. Essentially, the schema was using a snapshot of the GROUP_BY_MAP from the time it was imported. So third party taskgraph code that attempted to then add additional functions, would fail validation as the schema has already been built.
By moving this logic to an external utility module, it allows external consumers to register their custom functions prior to the schema being built.

fix: move group-by logic to utility file

---

src/taskgraph/run-task/run-task
test/test_scripts_run_task.py

This pull request is there to fix the issue:
https://github.com/taskcluster/taskgraph/issues/7
@JohanLorenzo : thanks for your help and advices. Can you review my PR? :)

Fix: dump python version number in run task

---

src/taskgraph/run-task/run-task

This works around recent issues found when starting from an older cached checkout - more details in the comments.
@jcristau - I ended up making this pretty targeted to avoid pulling tags in unwanted scenarios. I think it covers the case we ran into today at the very least? (Which, for posterity, was a task starting from a worker that had cached a checkout before the tag existed, then run a `github-release` task that wanted to checkout the tag.)

Fetch tags during run-task's git checkout in some scenarios

---

src/taskgraph/actions/add_new_jobs.py
src/taskgraph/actions/retrigger.py

Pass the suffix as a string to `create_tasks`.
Fixes #267

Fix regression in add-new-jobs and retrigger actions

---

src/taskgraph/transforms/job/common.py

It existed in gecko until bug 1527313
(https://hg.mozilla.org/mozilla-central/rev/fbe3fcbb31d84b3edeace2fd19250dd1d2711225) but has always been unused here, as far as I can tell.

Delete unused docker_worker_add_workspace_cache function

---

src/taskgraph/transforms/task.py

This feature was added to generic worker in https://github.com/taskcluster/taskcluster/pull/6148.
Only thing I wasn't sure on here was whether or not to include [this block](https://github.com/taskcluster/taskgraph/blob/d2a4cd791e9dea2dc8355585588daec5320c71a8/src/taskgraph/transforms/task.py#L445-L452).

feat: add `purgeCaches` option to gw payload builder

---

docs/reference/transforms/from_deps.rst
src/taskgraph/util/dependencies.py
test/test_transforms_from_deps.py

I found a need for this while working on Translations, where there are multiple leaf nodes at the end of the graph - and having a single task that includes them all makes it easy to target everything.

Add support for `all` grouping in `from_deps`

---

src/taskgraph/run-task/run-task

The typing module is not available in Python versions < 3.5 so the panic block is never reached and the explanatory message is never displayed.
https://firefox-ci-tc.services.mozilla.com/tasks/EDvGiDnpS7y00s0QitGIzQ/runs/0/logs/public/logs/live.log#L21

Import typing *after* Python deprecation panic

---

src/taskgraph/run-task/robustcheckout.py

Includes changes from
https://hg.mozilla.org/hgcustom/version-control-tools/rev/65ac4b5986df and https://hg.mozilla.org/hgcustom/version-control-tools/rev/d8ea98788e5f

run-task: update robustcheckout.py

---

src/taskgraph/config.py
src/taskgraph/transforms/task.py
test/test_transforms_task.py

This has come up with the work on our Translations model training pipeline. Full training runs are expected to take weeks or even a month to complete. Easily allowing the entire graph to have a longer deadline is the easiest way to cope with this, and I imagine other things could benefit as well, eg: fuzzing.

feat: allow overriding default task deadline

---

src/taskgraph/transforms/task.py

The task transform module keeps registries of payload and index builders, identified by a "name" string; AFAICT nothing prevents registering different functions under the same name, which seems potentially confusing.

Bug 1844298 - assert payload/index builders names are unique

---

docs/reference/parameters.rst
src/taskgraph/generator.py
src/taskgraph/parameters.py
test/test_generator.py

The driver behind this change is that in Gecko we want to always add 'docker-image' tasks even when `enable_always_target` would otherwise be False for all other kinds.
This will allow us to default to `enable_always_target: ["docker-image"]`, and then upgrade to `enable_always_target: True` on autoland or try.

feat: allow 'enable_always_target' parameter to accept a list of kinds

---

docs/reference/transforms/index.rst
docs/reference/transforms/task_context.rst
src/taskgraph/transforms/job/run_task.py
src/taskgraph/transforms/task_context.py
src/taskgraph/util/templates.py
test/data/command_context.yaml
test/data/task_context.yml
test/test_transform_task_context.py
test/test_transforms_job.py
test/test_transforms_job_run_task.py

While working on the Firefox Translations training pipeline I created a couple of very general transforms that had the effect of allowing substitution values into any part of a task definition. These values could be defined in the task templates themselves, or come from parameters. Both of these were inspired by the `command_context` support we already have in core Taskgraph, but take the idea much, much further.
My philosophy while working on this was to try to avoid kind-specific transforms at all costs, which meant having more generalized transforms that pushed some logic into the kinds via their configuration.
This pull request is a close-to-upstreamable version of those transforms. I'm not even sure we _want_ to support this here, so this is very much a draft at the moment, to be …

Much more broad support for task substitution

---

.taskcluster.yml
template/{{cookiecutter.project_name}}/taskcluster.github.yml

This is a new feature of Taskcluster Github that will attempt to automatically cancel tasks associated with a pull request after force pushing.

ci: enable 'autoCancelPreviousChecks' policy

---

docs/reference/transforms/from_deps.rst
src/taskgraph/transforms/from_deps.py
src/taskgraph/transforms/job/__init__.py
test/test_transforms_from_deps.py

This came out of a long discussion that @ahal and I had about #294, where [we concluded that it would be better](https://github.com/taskcluster/taskgraph/pull/294#discussion_r1283529826) to have `from-deps` handle `fetches` than have a specialized transform that only deals with setting dependencies & fetches when an upstream task is chunked.

feat: Support `fetches` and `set-name` in `from_deps`

---

src/taskgraph/transforms/from_deps.py

The former is arguably more than a "fix" in that it changes `from-deps` in a way that it is no longer the sole thing that manages upstream dependencies. In my opinion, if we are considering `from-deps` the official way to collect results from chunked/parallelized tasks, this is a necessary change, as we cannot predict the other things that such tasks may also depend on.
The latter is a pure bug fix: we shouldn't add a `fetch` block for kinds that have no `fetches` listed in `from-deps`.
(I can separate these two if it's useful.)

fix: from-deps: don't override all existing dependencies; don't add fetch entry for kinds without fetches

---

src/taskgraph/run-task/run-task

This is needed now as I'm using an ed25519 key to clone a private repo and it's failing verification.
The fingerprints are from:
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints

fix(run-task): add additional Github ssh fingerprints to run-task

---

src/taskgraph/main.py

Although rare, in certain cases taskgraph can cause OOMs if generating too many graphs in parallel.

feat: allow setting the maximum number of workers to use for taskgraph operations

---

docs/concepts/transforms.rst
docs/howto/create-tasks.rst
docs/howto/index.rst
docs/tutorials/getting-started.rst
docs/tutorials/index.rst

We already have tutorials that cover building a `.taskcluster.yml` and `taskcluster` dir, however they do so from scratch and were created prior to the existence of `taskgraph init`.
This adds a tutorial for all the impatient people who just want to see tasks running and don't care about how things work.

docs: add a new tutorial that uses 'taskgraph init'

---

src/taskgraph/docker.py

- import `IndexSearch` from the right place
- pass missing deadline argument to `should_replace_task`
- fix error message to not refer to mozilla-central

Fix load-image with an image name

---

taskcluster/docker/decision-mobile/Dockerfile

reference-browser is hitting bustage trying to update to Gradle 8 because it depends on Java 17 and the decision images are still running 11.

Bug 1854152 - switch mobile decision image to Java 17

---

src/taskgraph/run-task/run-task

As of Git 2.35.2, a security feature to mitigate a CVE on multi-user setups:
https://github.blog/2022-04-12-git-security-vulnerability-announced/#cve-2022-24765
Basically Git will error out if the checkout dir isn't owned by the current user. This impacts `run-task` because checkouts can come from caches meaning they were cloned by a different task user.
As long as we aren't sharing caches across levels or pools (which we aren't), that other user is just as trusted as the current one. So it's safe to disable this check.
Issue: #345

fix: bypass Git's safe directory feature in 'run-task'

---

src/taskgraph/main.py
template/cookiecutter.json
template/{{cookiecutter.project_name}}/taskcluster/ci/config.yml
test/test_main.py

fix(init): don't rely on local clone name for configuration

---

taskcluster/docker/index-task/Dockerfile
taskcluster/docker/index-task/package.json
taskcluster/docker/index-task/yarn.lock

Node 16 hit EOL on 2023-09-11.
Release schedule here https://nodejs.dev/en/about/releases.
This PR also bumps the `taskcluster-client` to v55

chore(deps): upgrade index-task image to node v18

---

src/taskgraph/util/taskcluster.py

This means we log the entire error message instead of just the http status code.

Log the body of taskcluster errors

---

template/{{cookiecutter.project_name}}/taskcluster.github.yml

While some trust domains (like Gecko) might want to share checkout caches across projects, typically projects are not related code bases to one another. So we probably don't want to share checkout caches by default.

fix(init): use project specific checkout cache by default

---

src/taskgraph/util/hash.py

Hey! :) 
I just did setup taskgraph locally on a windows machine, and wanted to run the full moz-vpn taskgraph. That it was trying to match `taskcluster/scripts/toolchain/compile_openssl.ps1` vs the windows path `taskcluster\scripts\toolchain\compile_openssl.ps1` therefore failed :c

Normalize Path Separator in util.hash.py

---

src/taskgraph/main.py

This is port from `gecko_taskgraph`: https://phabricator.services.mozilla.com/D127874 and https://phabricator.services.mozilla.com/D136515

Don't complain if parameters are only found on one side when running taskgraph --diff`

---

docs/tutorials/connecting-taskcluster.rst
taskcluster/ci/docker-image/kind.yml
taskcluster/docker/decision-mobile/Dockerfile

Consumers have stopped using java in their decision task, so this is no longer necessary.

Bug 1865788 - retire decision-mobile docker image

---

src/taskgraph/transforms/job/common.py
src/taskgraph/transforms/task.py
src/taskgraph/util/parameterization.py
test/test_transforms_job_run_task.py
test/test_util_parameterization.py

Sharing the same vcs checkout/storage dirs across different tasks running on different docker images runs the risk of incompatilibities, as shown e.g. when cloning a hg repo with one version of mercurial then trying to re-use it later using an older version.
Splitting by docker image means we lose some of the benefits of shared storage, but is safer in the face of tasks with (from taskgraph's point of view) unknown/arbitrary tool versions.  In practice this is hopefully good enough because there are few enough different docker images compared to the number of downstream tasks.
This requires a way to parametrize the cache name in the full task graph (at which stage in-tree docker images aren't resolved yet); we make it so that `{"task-reference": {"<foo>": "bar"}}` works and resolves …

Split docker-worker caches by docker image (bug 1866109)

---

README.rst
docs/reference/migrations.rst
pin-helper.sh
pyproject.toml
requirements/base.txt
requirements/docs.txt
setup.py
taskcluster/ci/docker-image/kind.yml
taskcluster/ci/tests/kind.yml
test/test_util_docker.py
tox.ini

Python 3.7 is EOL and we are on the verge of dropping support for it in Gecko.

Drop support for Python 3.7

---

src/taskgraph/transforms/__init__.py
test/test_transforms_notify.py

BREAKING CHANGE: removed `taskgraph.transforms.release_notifications` shim

refactor!: remove 'release_notifications' backward compat shim

---

src/taskgraph/config.py
src/taskgraph/generator.py
test/fixtures/gen.py
test/test_morph.py

BREAKING CHANGE: root dir should now point to the 'taskcluster' dir rather than 'taskcluster/kinds'.
This only impacts projects that use `taskgraph.config.load_graph_config` or `taskgraph.generator.TaskGraphGenerator` directly.

refactor!: change 'root_dir' to point to main 'taskcluster' directory

---

CONTRIBUTING.rst

This turned the operation into a no-op, a plain `pytest` call finds the tests just fine.

docs: remove explicit directory from the Pytest run

---

test/fixtures/gen.py
test/test_transforms_cached_tasks.py
test/test_util_cached_tasks.py

In https://github.com/taskcluster/taskgraph/pull/389 I'm making some changes to how cached tasks work, but there's no pre-existing tests. So this PR is adding tests to make that one easier to validate.

test: add tests for cached_task transforms and utility file

---

src/taskgraph/util/cached_tasks.py
test/test_util_cached_tasks.py

fix: ensure pull-requests properly use cached tasks

---

.codespell-ignore-words.txt
docs/concepts/optimization.rst
docs/reference/optimization-strategies.rst
src/taskgraph/transforms/run/__init__.py
src/taskgraph/transforms/task.py
src/taskgraph/util/cached_tasks.py
src/taskgraph/util/shell.py
src/taskgraph/util/vcs.py

These were surfaced by a `pre-commit` autoupdate PR (so they aren't raised currently, but are blocking upgrades to our lint dependencies)

ci: fix misc lint issues

---

src/taskgraph/main.py
test/test_main.py

This was causing directories like `my_repo.git_taskgraph` to be created.

fix(init): strip '.git' out of repo_url if it exists

---

src/taskgraph/config.py
src/taskgraph/transforms/docker_image.py
src/taskgraph/transforms/fetch.py
src/taskgraph/transforms/task.py
test/fixtures/gen.py
test/test_transforms_task.py

fixes #392 
fixes #393 
fixes #350
fixes #351

Allow expiration to be overridden in fetch and docker-image kinds. Allow setting the default expiry on "try" tasks

---

src/taskgraph/util/taskcluster.py
test/test_util_taskcluster.py

This can be useful in places like action tasks where you don't have access to a generated task graph, or where the tasks you're interested in (eg: to help optimize other tasks away) may span over a large number of task groups.

feat: add helper to walk up a task graph through the Taskcluster API

---

src/taskgraph/files_changed.py
test/test_files_changed.py

Makes more sense to get an http exception rather than a json decode error.

Call raise_for_status on hg.mozilla.org json-automationrelevance response

---

taskcluster/kinds/push-image/kind.yml

This is implicitly set by the `docker.py` file when you use an in-tree Docker image.

ci: don't use 'docker-image' as dependency name

---

.taskcluster.yml

"tasks_for" can now be "pr-action", which runs as level1 and asserts a scope based on the base repo instead of head.

Add support for pr-action in .taskcluster.yml (bug 1641282)

---

.taskcluster.yml

PR actions need to know both the base repo and branch to check out.

ci: add push.base_branch to tc.yml (bug 1641282)

---

src/taskgraph/util/archive.py
test/test_util_archive.py
test/test_util_docker.py

This is mostly copy/pasting from https://searchfox.org/mozilla-central/source/python/mozbuild/mozpack/archive.py, with a couple of tweaks because we don't have the mozpack `file` classes here.
The enchancements come from https://bugzilla.mozilla.org/show_bug.cgi?id=1807872 and https://bugzilla.mozilla.org/show_bug.cgi?id=1347582.

fix: pick up upstream enhancements for tarfile reproducability (fixes #421)

---

src/taskgraph/actions/add_new_jobs.py
src/taskgraph/actions/rebuild_cached_tasks.py
src/taskgraph/actions/retrigger.py
src/taskgraph/actions/util.py

The decision task id is the action task's group id, so it's already available without a round-trip through the tc index.  This helps in case of e.g. PRs that don't necessarily index decision tasks (and even if they do, don't index them where `find_decision_task` is currently looking for them).

actions: support non-indexed decision tasks

---

.taskcluster.yml
template/{{cookiecutter.project_name}}/taskcluster.github.yml

We were previously setting this to the tag of the release, but run-task doesn't handle the case where base_ref is a tag well. This could be fixed, but the release tag is the `head_ref` rather than the `base_ref`. So it's best to just not pass it in at all in this case.

fix(init): Don't set 'base_ref' on github-release events

---

src/taskgraph/morph.py
test/test_morph.py

While this isn't needed for Taskgraph operation, it makes testing morphs difficult as test functions are unable to call the decorated functions directly.

fix(morph): return original function in 'register_morph' decorator

---

.pre-commit-config.yaml

I find every week is a bit too much busy work for my liking. The next smallest time period is monthly.

ci: set pre-commit autoupdate schedule to monthly

---

src/taskgraph/transforms/from_deps.py
src/taskgraph/util/set_name.py
test/test_transforms_from_deps.py

This is useful in cases where many tasks are only distinguished by a common suffix, and have a common task downstream of them.
As a concrete example, in Translations, tasks are named after their kind + the language pair they're running against, and I'm working on getting beetmover running against all of them. At the moment, `from-deps` generate names like `beetmover-ru-en` for every single task, causing collisions.
Note that we already do this sort of naming for things like beetmover and signing tasks in Firefox, where we end up with task names like `beetmover-repackage-macosx64-shippable/opt` and `shippable-l10n-mac-signing-macosx64-shippable-17/opt`. (We don't use `from-deps` there, but this or similar support is likely to be needed to every move to it.)

feat: more featureful set-name for from-deps

---

src/taskgraph/optimize/base.py
src/taskgraph/optimize/strategies.py
src/taskgraph/util/taskcluster.py
test/test_optimize.py
test/test_optimize_strategies.py

Batching queries to get from task index to status reduces the number of (sometimes trans-continental) queries from 2*900+ to ~2. This reduces the time spent replacing tasks from 20% to 75% depending on the use-case.
The 20% improvement in wall time was observed when running `mach taskgraph morphed` in a CI worker, while the 75% improvement was observed in a developer machine in France running `mach taskgraph full`.
More information in https://github.com/taskcluster/taskcluster-rfcs/pull/189.

feat: use new batched queries in task replacement

---

src/taskgraph/docker.py
src/taskgraph/optimize/strategies.py
test/test_optimize_strategies.py

This patch removes the need for migrating all call sites, especially in `gecko`.
This is the result of more discussion following the two previous patches¹. Turns out that while duck typing in interfaces is not great, leaking implementation details to the user is probably worse.
[1] 41a10aaf10dbe5cfe3c5cb3fc3622bcdce8c66f5
[1] 5207917d69793784b9556716fc0a7279d26bd23a

feat: allow for both batched and single queries in task replacement

---

src/taskgraph/transforms/run/toolchain.py
test/test_transforms_run_toolchain.py

I encountered a minor annoyance while writing a toolchain job that tries to use a relative path like this:
```
flatpak-sdks:
description: "Flatpak Bundle SDKs"
treeherder:
symbol: TL(flatpak-sdks)
run:
use-caches: true
script: ../podman-worker.py
arguments:
- '/root/bundle_sdk.sh'
toolchain-alias: flatpak-sdks
toolchain-artifact: public/build/flatpak-sdks.tar.xz
```
This results in an error when trying to compute the file hashes, because it winds up failing to match `taskcluster/scripts/toolchain/../podman-worker.py` against the globbed path of `taskcluster/scripts/podman-worker.py` to work around the path we should run `path.normpath()` on the script before passing it into `hash_paths()`

Permit relative script paths in toolchain jobs

---

src/taskgraph/util/verify.py
test/test_util_verify.py

PR #3662 introduced `on-defined`, `on-pending` and `on-running`, and deprecated `on-any` in favor of `on-transition` or `on-resolved`.

Update verify_routes_notification_filters for Taskcluster > 37.5.0

---

src/taskgraph/util/copy.py
src/taskgraph/util/templates.py
test/test_util_copy.py
test/test_util_templates.py

This upstreams a pair of changes to this file, one of which is breaking.

Upstream some fixes in `taskgraph.util.templates` from gecko_taskgraph

---

src/taskgraph/transforms/cached_tasks.py
test/test_transforms_cached_tasks.py

Chain of trust being enabled or disabled influences the outcome of a task. Specifically, it controls whether or not chain of trust artifacts will be present on the task. Without this impacting the cache digest, cached tasks will continue to be cached when chain of trust is enabled on them, and if there is a chain of trust verifier downstream, this will cause verification issues.
BREAKING CHANGE: worker.chain-of-trust now influences cache digests

fix: chain of trust should influence cache digest

---

src/taskgraph/decision.py
src/taskgraph/optimize/base.py
src/taskgraph/optimize/strategies.py
test/test_optimize_strategies.py

This adds an separate log for optimizations that is always at `DEBUG` level. This allows us to more easily debug unexpected optimization behaviours after the fact. This is particularly helpful when an optimization behaves differently at different points in time, eg: when something is optimized away because task deadline exceeds the expiry time on a cached task.
Optimization log messages are retained in the regular task log, and respect that log's level. This behaviour is demonstrated in the decision of this PR (which runs with `--verbose`). There's also [a decision task without --verbose](https://firefox-ci-tc.services.mozilla.com/tasks/Ir93dO7dTc677dVD9TeR_A#artifacts) which demonstrates the main log printing only `INFO` messages, while `optimizations.log` additionally contains `DEBUG` …

feat: add a separate log for optimizations (fixes #523)

---

src/taskgraph/util/taskcluster.py

POST requests aren't retried by default, because they may not be idempotent.  However both find_task_id_batched and status_task_batched are read-only so there's no reason not to retry.

Bug 1904784 - retry batched taskcluster requests

---

src/taskgraph/transforms/run/__init__.py
src/taskgraph/transforms/task.py
test/test_transforms_task.py

The run and task transforms only allowed using the default per-project priority.

feat: allow setting per-task priority

---

src/taskgraph/util/readonlydict.py
test/test_util_readonlydict.py

The mozbuild version of ReadOnlyDict has a few extra dunder methods that allow copying and pickling it. This discrepency caused some regressions in mozilla-central when we switched over to using the Taskgraph version of it in bug 1901281.
Bug: 1903576

fix: update ReadOnlyDict to match latest mozbuild vendor

---

src/taskgraph/transforms/run/__init__.py
test/test_transforms_run.py

This allows for toolchains for things such as Python wheels to be fetched without being extracted in the wake of https://github.com/taskcluster/taskgraph/pull/541

feat: support fully configured fetches for toolchain and fetch upstreams

---

src/taskgraph/transforms/run/__init__.py
test/test_transforms_run.py

Technically not a regression, but a pretty serious oversight in #545

fix: make sorting work for toolchain and fetch tasks defined as dicts

---

src/taskgraph/util/vcs.py
test/test_util_vcs.py

Because git detects file renames, they have a custom way of handling it in diffs and a custom filter for it. Using `--no-renames` gets git to behave like mercurial here and show a renamed file as a removal of the old name and an addition of the new one.

Fix renames not getting detected as file changes on git

---

src/taskgraph/taskgraph.py

This was a small oversight in https://github.com/taskcluster/taskgraph/pull/264; TaskGraph.tasks is quite clearly a dict, as evidenced by code such as:
```
for task_label in self.graph.visit_postorder():
task = self.tasks[task_label]
f(task, self, *args, **kwargs)
```

fix: typedef for TaskGraph.tasks

---

docs/reference/migrations.rst
src/taskgraph/transforms/run/run_task.py

BREAKING CHANGE: Path to Python installation on MacOS no longer hardcoded.

fix!: stop hardcoding path to Python in MacOS generic-worker tasks

---

src/taskgraph/util/taskcluster.py
test/test_util_taskcluster.py

This can happen when attempting to fetch tasks (either directly or indirectly) that have expired. My view on this is that such tasks should be treated as no longer being dependencies since they no longer exist.
I can see a case for maybe making this optional behaviour, but I don't know of any use cases where we'd want to raise an exception for this case. Certainly when being used as part of actions or other CI code it ends up being a ticking time bomb.

fix: get_ancestors should ignore 404s

---

src/taskgraph/__init__.py
test/test_transforms_task.py

https://github.com/taskcluster/taskcluster/issues/7151 increased this

feat: bump max dependencies to 9,999

---

src/taskgraph/config.py
test/test_config.py

I keep tripping up over the fact that `graph_config` isn't a dict and trying to use things like `get`. Maybe we should make it subclass a dict, but for now simply implementing `.get()` will solve most of my problems.

feat(config): implement 'get()' for GraphConfig

---

src/taskgraph/run-task/run-task

This fixes using `run-task` in privileged podman containers

Don't chmod /dev/kvm if it already has the right mode

---

src/taskgraph/optimize/base.py
test/test_optimize.py

Some optimization strategies can take class level kwargs (such as the 'split_args' kwarg for all composite strategies).
Ensure these get forwarded when using the 'register_strategy' decorator.

fix(optimize): support kwargs in 'register_strategy' decorator

---

CHANGELOG.md
src/taskgraph/__init__.py
taskcluster/docker/decision/system-setup.sh

This was regressed by the switch to `uv` for packaging in the Decision image.

fix(decision): ensure 'taskgraph' is on the $PATH in Decision image

---

src/taskgraph/run-task/fetch-content
test/test_scripts_fetch_content.py

This patch improves the logic of static URL fetch tasks to better be able to determine if a file simply needs to be renamed, or if it is an archive that needs to be repackaged.
---
I was attempting to add the following fetch task to Firefox CI:
```
translations.esen.model:
description: The Spanish to English translation model artifact (version 1.0)
fetch:
artifact-name: model.esen.intgemm.alphas.bin
type: static-url
url: https://firefox-settings-attachments.cdn.mozilla.net/main-workspace/translations-models/9ee26e91-9b52-44ba-8d30-c0230dd587b2.bin
sha256: 4b6b7f451094aaa447d012658af158ffc708fc8842dde2f871a58404f5457fe0
size: 17140755
```
The issue is that the downloaded artifact (`dl_path`) is `9ee26e91-9b52-44ba-8d30-c0230dd587b2.bin`, however the desired artifact-name (`path`) is …

fix: Improve command_static_url repack archive logic

---

taskcluster/docker/decision/system-setup.sh

We don't want to leave a root-owned cache in the worker user's HOME directory.

fix(decision): add --no-cache to another uv command

---

src/taskgraph/run-task/run-task
taskcluster/docker/decision/system-setup.sh
test/test_scripts_run_task.py

This was causing problems, as the `worker` user was trying to create the same file, but it already existed and was owned by `root`.
Ensure we don't leave these lying around.

fix(decision): cleanup temporary uv lockfiles

---

src/taskgraph/run-task/fetch-content

In #591 I implemented a new function [should_repack_archive](https://github.com/taskcluster/taskgraph/blob/70654ce321c7b1bea7553895dc9a02c78757dab8/src/taskgraph/run-task/fetch-content#L438-L473) that aimed to improve the robustness of renaming files while preserving the preexisting logic of when to repack an archive in a fetch task. 
Unfortunately, I left an outer if-statement that leaves one edge case in which the behavior is slightly changed.
Whenever `args.strip_components` or `args.add_prefix` is defined, we are supposed to repack the archive regardless, however the new logic stays to do it only if the files are not the same. 
The logic is correct within the new function, but the outer if-statement needs to be removed.

fix: ensure strip_components and add_prefix are respected in repack_archive

---

src/taskgraph/actions/util.py

Projects on github don't have a meaningful pushlog-id, so we don't use it in the index path for action tasks.  When building the label-to-taskid mapping for a revision, look up action tasks in the index using the head_rev, where we can actually find them.
This can potentially do the wrong thing if a revision is pushed to two different branches, where we'd be mixing up the graphs, but we don't currently include the branch name in the index paths.

actions: look up action tasks by revision in fetch_graph_and_labels

---

docs/howto/run-locally.rst
src/taskgraph/parameters.py
test/test_parameters.py

Currently we support finding the decision task id based on `project`, from the index, but sometimes we want to find other types of ids (e.g for cron decision tasks).

feat(cli): support --parameters=index:<index path>

---

src/taskgraph/create.py
src/taskgraph/run-task/run-task

This fixes the two places where taskgraph assumed the proxy would be running on `http://taskcluster` instead of looking at the `TASKCLUSTER_PROXY_URL` environment variable.

Don't assume the proxy is running on `http://taskcluster`

---

docs/reference/optimization-strategies.rst
src/taskgraph/optimize/strategies.py
test/test_optimize_strategies.py

If we want a little more flexibility, we could add an additional optional parameter to turn this behavior on or off (there _might_ be some utility in tasks that strictly only run if some files changed, so that you can trigger all tasks with cron and those will be optimized away).

Do not apply skip-unless-changed for cron triggers.

---

.taskcluster.yml
template/{{cookiecutter.project_name}}/taskcluster.github.yml

project name is mainly used in routes, which require specific scopes to be set. Because of this, we should always use the `base` version of this. In cases where the `head` repository has a different name this ends up breaking things like actions in PRs.

fix: use base repo for project name in github .taskcluster.yml template

---

.github/workflows/pypi-publish.yml
CONTRIBUTING.rst

This just ensures we don't accidentally publish the wrong package on the wrong release. The pypi-publish action should do this already, but doesn't hurt to have an extra safeguard.

Use separate Github environment for releasing pytest-taskgraph

---

taskcluster/self_taskgraph/custom_target_tasks.py
taskcluster/test/params/main-repo-release-pytest-taskgraph.yml
taskcluster/test/params/main-repo-release-taskcluster-taskgraph.yml

This ensures that the proper head ref is detected whether it is prefixed with `refs/tags/` or not. This also updates the test params to reflect reality.

chore: fix head_ref detection in 'release' target tasks method

---

src/taskgraph/run-task/fetch-content
test/test_scripts_fetch_content.py

The latter was removed in python 3.13.

fetch-content: use urlopen's context parameter instead of cafile

---

pyproject.toml
src/taskgraph/run-task/robustcheckout.py

This reverts a couple of local changes, back to what's in v-c-t.

run-task: update our copy of robustcheckout hg extension

---

src/taskgraph/docker.py
src/taskgraph/util/archive.py
src/taskgraph/util/docker.py
test/test_util_docker.py

With an increasing number of docker images, the overhead of hashing the compressed contents of the docker context tars becomes visible when loading the toolchain kind during Firefox builds. But the really interesting part for the hash is the uncompressed contents. Whether they are compressed with gzip at level 9, gzip level 1, bz2 or zstd, it doesn't matter for the resulting docker image. So it makes sense to only hash the uncompressed contents, which is much faster.

Hash the uncompressed contents of docker context tar

---

src/taskgraph/run-task/run-task
src/taskgraph/transforms/run/__init__.py
src/taskgraph/transforms/run/common.py
src/taskgraph/transforms/run/run_task.py
test/test_scripts_run_task.py
test/test_transforms_run_run_task.py

We currently hard code some environment variables that should be turned into absolute paths. But it would be great if we had the ability to do this for any environment variable.
My current use case is setting `PIP_CACHE_DIR` to an absolute path under the task's workdir. I could add it to the list of hard coded envs, but it would be better to do something like `PIP_CACHE_DIR=$TASK_WORKDIR/.cache/pip` and have run-task do the interpolation automatically.

[run-task] Support interpolating `$TASK_WORKDIR` in environment variables

---

src/taskgraph/util/taskcluster.py
test/test_util_taskcluster.py

BREAKING CHANGE: `get_ancestors` now returns a dict of task_id to label rather than label to task_id
This allows it to give a complete list of ancestors in graphs that have multiple tasks with the same label.

fix: return tasks by task_id in get_ancestors to avoid collisions in labels

---

docs/reference/migrations.rst
packages/pytest-taskgraph/src/pytest_taskgraph/fixtures/gen.py
src/taskgraph/config.py
src/taskgraph/transforms/run/common.py
src/taskgraph/transforms/run/run_task.py
src/taskgraph/util/caches.py
taskcluster/docker/python/Dockerfile
taskcluster/kinds/check/kind.yml
taskcluster/kinds/codecov/kind.yml
taskcluster/kinds/doc/kind.yml
taskcluster/kinds/test/kind.yml
test/test_transforms_run.py
test/test_transforms_run_run_task.py

This is an overhaul of how we set up caches in the run transforms. At a high level, this is:
1. Creating a new mechanism to register caches for common tools (pip, uv, npm, cargo)
2. Refactoring the existing checkouts cache to use this mechanism.
3. Providing task and project wide configs to include or exclude caches
4. Removing the `cache-dotcache` key
I recommend reviewing commit by commit.
Making this a draft PR for now so I have a chance to test it out with real tasks.

Bug 1937801 - Implement mechanism to use caches for common tools in run transforms

---

docs/howto/docker.rst

Describe the `parent`, `definition` and `args` entries supported by the docker_image transforms.

docs: add to docker howto

---

docs/reference/migrations.rst

chore: add migration guide for breaking change to get_ancestors

---

src/taskgraph/run-task/run-task

```
/usr/local/bin/run-task:118: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
now = datetime.datetime.utcnow().isoformat().encode("utf-8")
```
This slightly changes the output, replacing `Z` with `+00:00` for the timezone component.

run-task: silence python 3.12 deprecation warning

---

src/taskgraph/util/vcs.py

In case of branching or history rewrite, `{base_rev}~-1` is ambiguous and causes an error.

vcs: don't assume that the base rev has a single child

---

src/taskgraph/docker.py
test/test_docker.py

Avoid saying `Successfully built <image>` when it wasn't.

build-image: check exit code from docker build

---

docs/howto/docker.rst
docs/tutorials/creating-a-task-graph.rst

See https://github.com/codespell-project/codespell/pull/3445

docs: keep codespell happy (re-used → reused)

---

src/taskgraph/transforms/task.py

To align with https://github.com/taskcluster/taskcluster/pull/7505.

feat: add `run-task-as-current-user` gw payload builder option

---

docs/reference/migrations.rst
src/taskgraph/run-task/run-task
src/taskgraph/transforms/run/__init__.py
src/taskgraph/transforms/run/common.py
test/test_scripts_run_task.py
test/test_transforms_run_run_task.py
uv.lock

In hindsight, this ended up being a bad idea and caused lots of subtle issues in Gecko. As an alternative, I landed a change to get generic-worker itself to set $TASK_WORKDIR.
This will take awhile to propagate to all pools, but in the meantime it's cleanest to revert back to the abspath method.

refactor!: revert {task_workdir} interpolation in run-task environment

---

src/taskgraph/config.py
test/test_util_schema.py

Allow 'level' as a key in task-priority config.
Extend the test_optionally_keyed_by function to include validation for multiple keys (foo, bar).
closes #252

feat: Allow task-priority to be keyed by level

---

src/taskgraph/main.py
test/test_main.py

The documentation already says `You can generate actions.json locally by running taskgraph actions.` however that command was never ported over from gecko's `./mach taskgraph actions`

feat: port `taskgraph action` from gecko_taskgraph

---

taskcluster/kinds/complete/kind.yml

These PRs are lacking codecov, but that doesn't seem bad enough to prevent running the `complete` task (which doesn't depend on codecov anyway).

ci: run complete-pr task on untrusted PRs

---

src/taskgraph/main.py
src/taskgraph/util/hash.py
src/taskgraph/util/vcs.py
test/test_util_vcs.py

Previously we were walking the file system and were e.g scanning files in the `.git` directory. This can be quite slow on larger repos.
Fixes #663

Only consider tracked files when building toolchain hashes

---

test/test_actions_rebuild_cached_tasks.py

This test failed intermittently if the generated task id happens to contain the string 'bar'

test: make 'test_action_rebuild_cached_task' more robust

---

src/taskgraph/transforms/task.py

Implemented upstream in https://github.com/taskcluster/taskcluster/pull/7598

feat: support volume artifact type for docker worker

---

src/taskgraph/transforms/run/run_task.py
test/test_transforms_run_run_task.py

The decision task knows the contents of these scripts so it can pass their checksums to downstream tasks.

Let generic-worker verify run-task/fetch-content integrity

---

.github/workflows/pre-commit-autoupdate.yml
.pre-commit-config.yaml

This replaces the pre-commit.ci app's autoupdate.
The one caveat with this is that it doesn't check for PRs that are already opened on that branch. I did that to keep it as simple as possible. It's not a real issue as github will detect that and close the previous PR and then open a new one but it might be a bit spammy if we don't merge those PRs

Add a workflow to run auto updates for pre-commit

---

src/taskgraph/docker.py
src/taskgraph/main.py
test/test_docker.py

This command is an extension of the `load-image` command. Given a taskId, it will:
1. Find and download the docker image from the parent task.
2. Spin up a docker container using this image.
3. Ensure environment variables in the task's definition are set.
4. Run the "setup" portion of `run-task` (checkouts, fetches, etc)
5. Drop the user into a bash shell.
This will make it easier to debug tasks locally. Note for now only tasks using run-task with a docker-worker (or D2G) payload are supported.

feat: implement new 'load-task' command to debug tasks locally

---

README.rst
docs/index.rst

setup.py doesn't exist anymore in the repo.

Update instructions to install package from local clone

---

src/taskgraph/actions/registry.py
test/test_actions_registry.py

The action task's scopes are tied to the head repo.

actions: fix scope check on mercurial (bug 1965754)

---

src/taskgraph/transforms/run/run_task.py
src/taskgraph/transforms/task.py
test/test_transforms_run_run_task.py

Fixes a regression from #666, which:
- used taskId instead of task-id in the task description
- failed to add sha256 to the schema

Fix run-task/fetch-content mounts definition

---

CHANGELOG.md
src/taskgraph/transforms/run/run_task.py
src/taskgraph/transforms/task.py
test/test_transforms_run_run_task.py

On top of the initial issue with the task schema not getting updated to match, it also causes failures because not all tasks have a direct dependency on the decision task, but generic-worker insists on that dependency existing when mounting an artifact from a task.  So go back to mounting by url.

Revert "Let generic-worker verify run-task/fetch-content integrity"

---

src/taskgraph/morph.py

This has apparently been the limit in Taskcluster since 2019, but we never noticed / bothered to update it here.

fix: bump MAX_ROUTES up to 64

---

docs/concepts/transforms.rst
docs/howto/index.rst
docs/howto/resolve-keyed-by.rst
src/taskgraph/util/keyed_by.py
src/taskgraph/util/schema.py
test/test_util_keyed_by.py
test/test_util_schema.py

I tested this in Gecko and it resulted in an identical full graph

feat: support lists in 'resolve_keyed_by'

---

src/taskgraph/transforms/run/__init__.py

This makes it easier to debug errors in your Taskgraph generation.
```
Exception: distillation-student-model-quantize-en-ru can't fetch inference-build artifacts because there are no tasks with label inference-build in kind dependencies!
Available tasks:
- toolchain-cuda-toolkit
- toolchain-cuda-toolkit-11
- toolchain-marian
- toolchain-marian-cpu
- toolchain-fast-align
- toolchain-preprocess
- toolchain-extract-lex
- toolchain-kenlm
- toolchain-cyhunspell
- corpus-merge-devset-en-ru
- build-vocab-en-ru
- inference-test
- inference-build-wasm
- inference-test-wasm
- distillation-corpus-build-shortlist-en-ru
- distillation-student-model-finetune-en-ru
```

Add the available labels when a kind dependency cannot be found

---

src/taskgraph/parameters.py
test/test_parameters.py

In commit df291c6e31b69daa2c9cb85879a2872f2d7480ca, root_dir was changed from a relative path to an absolute path, resulting in file_url() no longer detecting the path correctly as it didn't start with "comm/". This change allows file_url() to correctly detect and handle an absolute path that includes "comm/".

Update file_url() handling of Thunderbird comm paths

---

src/taskgraph/run-task/fetch-content

This function is used to decide whether we can use github directly to download the code without cloning the repository. That optimization only works if the repository doesn't have submodules.
Before this commit, if github returned any status code that wasn't a 2xx or 3xx, we would consider that the repository didn't have any submodule. This is fairly obviously wrong as a transient server error on the github side for example would mean that we'd assume that the repository doesn't have any submodules.
We now check for HTTPErrors and only consider that a repository doesn't have any submodule iif the status is 404 otherwise, something went wrong, log it and fallback to the non optimized path.
I also kept the bare exception but added some log to it, just in case.

Be a lot more conservative in _github_submodule_required

---

.github/workflows/pypi-publish.yml
docs/conf.py
docs/reference/source/taskgraph.transforms.rst
docs/reference/transforms/chunking.rst
docs/reference/transforms/from_deps.rst
docs/reference/transforms/matrix.rst
docs/reference/transforms/task_context.rst
packages/sphinx-taskgraph/pyproject.toml
packages/sphinx-taskgraph/src/sphinx_taskgraph/__init__.py
packages/sphinx-taskgraph/src/sphinx_taskgraph/autoschema.py
pyproject.toml
src/taskgraph/config.py
src/taskgraph/decision.py
src/taskgraph/parameters.py
src/taskgraph/transforms/chunking.py
src/taskgraph/transforms/docker_image.py
src/taskgraph/transforms/fetch.py
src/taskgraph/transforms/from_deps.py
src/taskgraph/transforms/matrix.py
src/taskgraph/transforms/notify.py
src/taskgraph/transforms/run/__init__.py
src/taskgraph/transforms/run/index_search.py
src/taskgraph/transforms/run/run_task.py
src/taskgraph/transforms/run/toolchain.py
src/taskgraph/transforms/task.py
src/taskgraph/transforms/task_context.py
src/taskgraph/util/schema.py
uv.lock

Alright this one is a bit silly, but it's something that's been bugging me for a really long time. First, this was partly made with AI. I used it to get the basic structure in place for a Sphinx extension that can modify only Schema instances. But then I made heavy manual modifications on top to get it to look the way I wanted and handle all sorts of edge cases.
Second, I don't expect any reviewers to actually dig in and understand how the autoschema.py works. I'm happy to walk through anything that folks want. But maybe a better way to illustrate what it's doing is with some before / after screenshots.
Before:
After:

Improve schema handling in documentation

---

src/taskgraph/docker.py

Actually retag images when a tag is passed to `taskgraph load-image`

---

src/taskgraph/run-task/run-task

```
/usr/local/bin/run-task:330: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
now = datetime.datetime.utcnow().isoformat().encode("utf-8")
```

run-task: replace another use of datetime.utcnow()

---

src/taskgraph/util/verify.py
test/test_util_verify.py

Makes an exception be thrown if a route contains a "/" and added tests for it. Closes #254

Check for slash in route

---

src/taskgraph/generator.py

In translations we have a really complicated taskgraph, and it's nice to output better debug information when things go wrong. With the debug information it's easy to see I should have used "compile" rather than "compile-marian-fork".
Error before:
```
Traceback (most recent call last):
File "/builds/worker/checkouts/utils/preflight_check.py", line 554, in <module>
main()
File "/builds/worker/checkouts/utils/preflight_check.py", line 522, in main
run_taskgraph(parsed_args.config, get_taskgraph_parameters())
File "/builds/worker/checkouts/utils/preflight_check.py", line 137, in run_taskgraph
taskgraph.actions.trigger_action_callback(
File "/usr/local/lib/python3.10/dist-packages/taskgraph/actions/registry.py", line 344, in trigger_action_callback
cb(Parameters(**parameters), graph_config, …
```

Add a more descriptive error when a kind cannot be found

---

src/taskgraph/docker.py

This would otherwise fail if the command contained shell meta-characters.

load-task: quote the command passed to `echo`

---

src/taskgraph/docker.py

The uid outside docker might not match the worker user in the container,
either due to namespaces or just not running as uid 1000, e.g. when
using podman I'm getting a root-owned 0600 .bashrc, meaning I can't
actually run exec-task.

docker: ensure .bashrc is readable by the worker user in load-task

---

src/taskgraph/config.py
src/taskgraph/docker.py
src/taskgraph/main.py
src/taskgraph/transforms/task.py
src/taskgraph/util/docker.py
taskcluster/config.yml
test/data/taskcluster/kinds/docker-image/kind.yml
test/test_docker.py
test/test_util_docker.py

Closes https://github.com/taskcluster/taskgraph/issues/21

fix: removed hardcoding from docker-image dir and kinds

---

src/taskgraph/config.py
src/taskgraph/parameters.py
test/test_config.py

Removing this exception should all for non-standard root directories to work. Closes #522. I am not sure exactly what this #522 is asking for, please correct me if interpretation was wrong

fix: removed exception for vcs root property 

---

src/taskgraph/transforms/from_deps.py
src/taskgraph/util/dependencies.py
test/test_transforms_from_deps.py
test/test_util_dependencies.py

Storing this on `from_deps` tasks allows us to avoid iterating over potentially all the task dependencies when finding it later, which can add up to a lot of time in larger graphs.
In a profile I ran for gecko taskgraph, `get_dependencies` (via `get_primary_dependency`) was the second hottest function. With this patch it moves down to 10th place, and takes 1/4 of the amount of time it used to.

feat: use `primary-dependency` attribute to find primary dependency of a task

---

src/taskgraph/generator.py

This race condition happens because `all_tasks` is updated in a callback, which runs asynchronously, but `kinds` and `edges` are updated in the main loop. This leads to a potential mismatch when the logic at the start of `submit_ready_kinds` runs: if `all_tasks` is updated but the other two are not, the data we feed into `load_tasks` will be incorrect.

fix: race condition in parallel kind processing

---

packages/pytest-taskgraph/src/pytest_taskgraph/fixtures/gen.py
src/taskgraph/generator.py
test/test_generator.py

While this worked very well on Linux, it causes issues anywhere we can't `fork` to get a new process (most notably on Windows). The problem lies in the fact that in these cases, we spawn an entire new process, which re-imports taskgraph from scratch. This is fine in some cases, but in any case where global state has been modified in an earlier part of `TaskGraphGenerator._run`, we lose whatever side effects happened there, and end up failing in some way.
Concretely: in gecko we add a bunch of `payload_builders` as part of registering the graph config. This code doesn't re-run in the spawned processes, so the payload builders don't exist there.
There are workarounds for this: for example, redoing all the earlier work of `_run` in each subprocess, or perhaps finding some way to ensure all …

revert: multiprocess kind processing

---

src/taskgraph/main.py

This fixes a regression from d2dee6ad6631b1d67255ff54f978e9e53ff11fb6 which added the graph config arg but then got the order wrong in these calls which lead to `TypeError: unhashable type: '_Environ'` in image_path when calling `taskgraph build-image`
```
Traceback (most recent call last):
File "src/taskgraph/main.py", line 1020, in main
return args.command(vars(args))
~~~~~~~~~~~~^^^^^^^^^^^^
File "src/taskgraph/main.py", line 593, in build_image
build_image(args["image_name"], args["tag"], os.environ, graph_config)
~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "src/taskgraph/docker.py", line 122, in build_image
image_dir = docker.image_path(name, graph_config)
File "src/taskgraph/util/docker.py", line 225, in image_path
paths = image_paths(graph_config) …
```

Fix parameter order for build_image/build_context in main

---

packages/pytest-taskgraph/src/pytest_taskgraph/fixtures/gen.py
src/taskgraph/generator.py
test/test_generator.py

This is especially useful when some of the kinds the caller is interested in is a dependency of another kind.

Add a function to get tasks from multiple kinds in one pass

---

src/taskgraph/config.py
src/taskgraph/decision.py
src/taskgraph/generator.py
src/taskgraph/util/python_path.py

`import_module` is newer, and provides a couple of advantages over a bare `__import__`:
> The import_module() function acts as a simplifying wrapper around importlib.__import__(). This means all semantics of the function are derived from importlib.__import__(). The most important difference between these two functions is that import_module() returns the specified package or module (e.g. pkg.mod), while __import__() returns the top-level package or module (e.g. pkg).
It's unclear if this will actually fix any problems in the real world, but there's no recent to use `__import__` at this point AFAICT.

fix: use importlib.import_module instead of `__import__`

---

src/taskgraph/util/taskcluster.py

As this code stands now the continuation token will never be used, and any continuation cases will result in an infinite loop.

fix: set continuation_token correctly in `find_task_id_batched`

---

packages/pytest-taskgraph/src/pytest_taskgraph/fixtures/gen.py
src/taskgraph/generator.py
test/test_generator.py

This is a slightly updated version of #738 + #744, which were backed out a few weeks ago due to not working correctly on Windows. In a conversation I had today it was suggested that we should just not support multiprocess on Windows so we can at least take the win elsewhere. This patch does that, and surely no other issues will arise...

feat: generate kinds in parallel across multiple processes

---

src/taskgraph/docker.py
src/taskgraph/main.py
test/test_docker.py

This makes it really nice to iterate on a docker image and test it against a live task, by using e.g:
```
taskgraph load-task <task-id> --image python
```
This will re-build the `taskcluster/docker/python` image, launch it in a container, and load `<task-id>` into it.

Add ability to use custom images in `taskgraph load-task`

---

pyproject.toml

The latter is deprecated in favor of the the former. This fixes a warning when running stuff with uv 
> warning: The `tool.uv.dev-dependencies` field (used in `pyproject.toml`) is deprecated and will be removed in a future release; use `dependency-groups.dev` instead

Use dependency-groups.dev instead of dev-dependencies in uv

---

.pre-commit-config.yaml
src/taskgraph/run-task/robustcheckout.py

This is third party code that gets pulled in periodically. Let's keep excluding it and revert the recent style fix.

style: exclude robustcheckout.py and revert changes
